Initial (semi) working version of the n2p2 package
ECP-copa/CabanaMD pull request #10
Opened 2019-06-25 23:35 UTC by saakethdesai

2019-06-26 00:36 UTC, junghans commented
I think it would be better to use CMake's External Project feature instead of copying the source into our repo.

Something like:
```cmake
include(ExternalProject)
ExternalProject_Add(p2n2_build
      URL https://github.com/CompPhysVienna/n2p2/archive/v1.0.0.tar.gz
      CONFIGURE_COMMAND "" 
      SOURCE_SUBDIR src
      BUILD_COMMAND make libnnp 
      BUILD_IN_SOURCE 1
      INSTALL_COMMAND ""
      )
ExternalProject_get_property(p2np_build SOURCE_DIR)
set(P2N2_LIBRARIES ${SOURCE_DIR}/src/libnnp.a)
set(P2N2_INCLUDE_DIRS ${SOURCE_DIR}/src)
add_dependencies(CabanaMD p2np_build)
```

2019-06-26 02:30 UTC, streeve commented
> I think it would be better to use CMake's External Project feature instead of copying the source into our repo.

That's a good point. @saakethdesai , can you switch to an external project and copy in only the files you need to modify (renamed appending with Cabana)?

2019-06-26 05:20 UTC, junghans commented
Another option is:
```cmake
include(FetchContent)
FetchContent_Declare(n2p2 GIT_REPOSITORY https://github.com/CompPhysVienna/n2p2.git GIT_TAG 1.0.0)
```

2019-08-03 00:04 UTC, streeve requested changes
The major thing to update before merging is removing the files unmodified from libnnp, linking them in from a separate build (just like we do with Kokkos/Cabana), overloading just the functions that you've replaced, and removing the rest. Eventually we can do a submodule, but let's focus on removing overlap first

2019-08-03 00:04 UTC, streeve commented on .gitignore
> -build
Revert

2019-08-03 00:04 UTC, streeve commented on src/cabanamd.cpp
> +
Spacing

2019-08-03 00:04 UTC, streeve commented on src/cabanamd.cpp
> +  if(input->comm_newton || input->force_type == 2) { //update force if nnp pair style
Use enum

2019-08-03 00:04 UTC, streeve commented on src/cabanamd.cpp
> +    if(input->comm_newton or input->force_type == 2) { //update force if nnp pair style
Also use enum

2019-08-03 00:04 UTC, streeve commented on src/cabanamd.cpp
> +    /*auto f = Cabana::slice<Forces>(system->xvf);
Remove

2019-08-03 00:04 UTC, streeve commented on src/force_types/force_nnp_cabana_neigh.h
> +          force = NULL;
Give some feedback to the user that this is not an option (for all 3)?

2019-08-03 00:04 UTC, streeve commented on src/read_data.h
> +        id(n) = id_tmp; type(n) = type_tmp-1; x(n,0) = x_tmp; x(n,1) = y_tmp; x(n,2) = z_tmp;
Maybe separate into a "fix read_data" PR

2019-08-03 00:04 UTC, streeve commented on src/system.h
> +  double cflength = 1.889726;
Move to input / force_nnp

2019-08-03 00:04 UTC, streeve commented on src/types.h
> +enum NNPNames { G = 0, dEdG = 1, energy = 2};
This should really be in force_nnp or mode, but I'm fine with it here for now

2019-08-03 00:04 UTC, streeve commented on src/property_pote.cpp
> +#include <iostream>
Is this necessary?

2019-08-03 00:04 UTC, streeve commented on src/libnnp/Mode.cpp
> +    printf("%d %f %f %f\n", id(0), x(0,0), x(0,1), x(0,2));
Remove prints

2019-08-03 00:04 UTC, streeve commented on src/force_types/force_nnp_cabana_neigh.cpp
> +  auto id = Cabana::slice<IDs>(system->xvf);
Unused slice

2019-08-03 00:04 UTC, streeve commented on src/libnnp/Mode.cpp
> +    auto id = Cabana::slice<IDs>(s->xvf);
Unused slice

2019-08-03 00:04 UTC, streeve commented on src/libnnp/Mode.cpp
> +    auto id = Cabana::slice<IDs>(s->xvf);
Unused slice

2019-08-09 00:43 UTC, streeve requested changes
Couple extra notes from our discussion

2019-08-09 00:43 UTC, streeve commented on src/libnnp/Mode.cpp
> +        for (int i = 0; i < numLayers; ++i)
Use deep_copy for each view

2019-08-09 00:43 UTC, streeve commented on src/libnnp/Mode.cpp
> +                if (AF[l] == 0)
Maybe View instead?

2019-12-13 17:55 UTC, streeve commented
@saakethdesai I think this is ready, let me know what you think

2019-12-16 02:22 UTC, streeve approved these changes

2019-12-17 03:26 UTC, merged