Flexible number of AoSoA and vector lengths
ECP-copa/CabanaMD pull request #30
Opened 2020-02-04 21:45 UTC by streeve

Enable split/combined AoSoA and change of vector length at build time with CMake options. Easy addition of additional AoSoA splits for either main particle properties or NNP per-atom variables

Closes #22

2020-02-11 22:07 UTC, streeve commented
For documentation: I hit a segfault when trying to use the `Cabana::gather` AoSoA variant. Since only the position and type need to be ghosted I've switched to the slice variant for now (and the other wrappers on Cabana AoSoA operations, `permute` and `migrate`, seem to work fine)

2020-02-18 12:14 UTC, sslattery commented
@streeve I see this is WIP - do you want a review?

2020-02-18 20:09 UTC, streeve commented
> @streeve I see this is WIP - do you want a review?

Yes, a review would be helpful, but I'm still trying to fix MPI bugs

2020-03-04 18:30 UTC, streeve commented
@sslattery I think I've fixed the previous issues with this by being more careful with my shared pointers. It's also much cleaner with the recent cmake updates

2020-03-05 21:52 UTC, sslattery requested changes
This looks pretty good to me. Mostly just some CMake cleanup and then a more philosophical discussion on how the polymorphism is designed. Although it should be noted that you were following the previous strategy in ExaMiniMD which gave fast compile times.

2020-03-05 21:52 UTC, sslattery commented on src/CMakeLists.txt
> +    message( FATAL_ERROR "Vector length must be a factor of 2 or equal to 1" )
This will get checked at compile time in a pretty clear way so you might not need these here as one could quickly reconfigure once they see the compile error.

2020-03-05 21:52 UTC, sslattery commented on src/CMakeLists.txt
> +  set(CabanaMD_LAYOUT_6AoSoA ON)
I would just do this in an `else()` below

2020-03-05 21:52 UTC, sslattery commented on src/CMakeLists.txt
> +    set(CabanaMD_LAYOUT_NNP_3AoSoA ON)
again could do in an `else()` below for the default behavior

2020-03-05 21:52 UTC, sslattery commented on src/CMakeLists.txt
> +      message( FATAL_ERROR "NNP vector length must be a factor of 2 or equal to 1" )
Same thing here - I would just leave this to the compile time check

2020-03-05 21:52 UTC, sslattery commented on src/cabanamd.cpp
> +    auto f = system->f;
nice - I like this structure

2020-03-05 21:52 UTC, sslattery commented on src/cabanamd.cpp
> +    system->slice_all();
internally does this just update the slices?

2020-03-05 21:52 UTC, sslattery commented on src/modules_system.h
> +#ifdef CabanaMD_LAYOUT_1AoSoA
Could we just have done runtime polymorphism with virtual functions or compile time polymorphism with template specializations here? He basically did configure-time polymorphism with this type of structure. Makes the code faster to build but it is confusing at first glance. We don't have to change now but might be useful to think about in the future as we continue to restructure. The interface and class-use structure you have will map perfectly to other types of polymorphism - I'd ultimately suggest runtime in this case though unless the `System` classes have functions which much be inlined and called on the device.

2020-03-05 21:52 UTC, sslattery commented on src/modules_system.h
> +#ifdef CabanaMD_LAYOUT_1AoSoA
OK now that I look below this is in fact doing runtime polymorphism. Why the `#ifdef` sequence here then? Is this basically a configure-time factory method?

2020-03-05 21:52 UTC, sslattery commented on src/types.h
> +#ifdef CabanaMD_LAYOUT_1AoSoA
OK so here is where you would really need compile-time polymorphism because these types differ and get used throughout the code. After reading through all of this I see why the configure-time macros are there. It makes it look like runtime polymorphism but you get only 1 implementation so you can do these typedefs. Ultimately I would advocate an implementation like `System<LAYOUTTYPE>` where the layout type tags are `1AoSoA`, `6AoSoA`, etc. Then you get the typing structure, general interface, the compiler only builds the implementation you want (which you would specify somewhere with your configure macros). The only downside is that now all of your classes are templated on a System type when they use a System. So you would get some extra compile overhead as a result.

2020-03-18 21:21 UTC, streeve commented on src/types.h
> +#ifdef CabanaMD_LAYOUT_1AoSoA
Just to update - I'm moving towards templating everything on System, itself templated on Layout. So these compilation flags will be replaced by runtime flags, but the veclen compile flags will remain

2020-03-18 21:22 UTC, streeve commented on src/cabanamd.cpp
> +    system->slice_all();
Yep

2020-03-20 21:36 UTC, streeve commented
@junghans any idea why clang-format thinks one file should have a completely different style? Thanks

2020-03-20 23:12 UTC, junghans commented
> @junghans any idea why clang-format thinks one file should have a completely different style? Thanks

Maybe windows line ending....

2020-03-21 03:42 UTC, streeve commented
Turns out the clang-format issue is a specific variant of Kokkos View declaration. @sslattery this should be ready for another review

2020-04-02 02:22 UTC, sslattery approved these changes
looks good - you have addressed my comments

2020-04-02 02:22 UTC, sslattery commented on src/cabanamd.h
> +template <class t_System>
is this subclass to hide the template?

2020-04-02 18:12 UTC, merged